// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF_3RAjONkhChkS2yiCy5uKyKxdv6Wi40',
    appId: '1:263316686375:web:99c51d434964f688a6b002',
    messagingSenderId: '263316686375',
    projectId: 'toolist-a53ee',
    authDomain: 'toolist-a53ee.firebaseapp.com',
    storageBucket: 'toolist-a53ee.appspot.com',
    measurementId: 'G-LN604TRNWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB39bJ8nLnUA3LlPNexOceadn7pRf17rXM',
    appId: '1:263316686375:android:09c1177592966a10a6b002',
    messagingSenderId: '263316686375',
    projectId: 'toolist-a53ee',
    storageBucket: 'toolist-a53ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7BkI8y7suHZBq_C14Xc1ODCONtXzd6Sg',
    appId: '1:263316686375:ios:ea00b3e86d18a8f2a6b002',
    messagingSenderId: '263316686375',
    projectId: 'toolist-a53ee',
    storageBucket: 'toolist-a53ee.appspot.com',
    iosBundleId: 'com.example.toolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7BkI8y7suHZBq_C14Xc1ODCONtXzd6Sg',
    appId: '1:263316686375:ios:aa10fff890252865a6b002',
    messagingSenderId: '263316686375',
    projectId: 'toolist-a53ee',
    storageBucket: 'toolist-a53ee.appspot.com',
    iosBundleId: 'com.example.toolist.RunnerTests',
  );
}
